---
title: "Module_4_data_viz"
author: "Ryan Godfrey"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##### Creating Graph #####
install.packages("tidyverse")#tidyverse
library(tidyverse)
install.packages("dplyr")#dont worry 
mpg
ggplot(data=mpg)+geom_point(mapping=aes(x=displ,y=hwy))#graph
```
####Format for GG plot

ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))

# Graphing in R####
```{r}
####ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, colour = class)) # 
##Changing colout 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), colour="blue")

#### Changing class #> Warning: Using size for a discrete variable is not advised.
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
#Changing class and colour
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class), colour="blue")

# Changing transparency 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))

#Changing shape 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```


```{r}
# Stringing all together 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class, alpha= class), 
             colour="blue")
```
#2.20 Facet and Panel Plots
```{r}
# plot one facet wrap
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
# plot 2 facet grid 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)
# plot 3 facent grid . better version
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(. ~ cyl)
```
#Facet Wrap Question
it chooses the rows and columns respectively. other codes that affect it are shrink which changes the scales and reorder which changes the order of the panels.
```{r}
#error was a x in displ
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))
#  geom_point(mapping = aes(x = displ, y = hwy)) # points horrible  # try smooth line
#adding drv
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv, colour=drv))+
  scale_colour_discrete() +
  geom_point(mapping = aes(x = displ, y = hwy, linetype = drv, colour=drv))+
  scale_colour_discrete()
```
```{r}
#subcompact
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + #much more effiecent
  geom_point() + 
  geom_smooth()
#way to much code 
ggplot() + 
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))
```


#Plotting stats
```{r}
#must load packages before running
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))

ggplot(data = diamonds) + 
  stat_count(mapping = aes(x = cut))


ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = stat(prop), group = 1))

#stat summary
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.min = min,
    fun.max = max,
    fun = median
  )

```
#Aesthetic Adjustments
```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, colour = cut))#color outside bars
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))#color inside bars 
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))#multiple colors in bar

ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity") #gradient of clarity

ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity") #no fill
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill") #I dont like this one

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")#overlappings

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")# shows points even if in spot
```
#the outline of coding aethetics 
```{r}
#ggplot(data = <DATA>) + 
 # <GEOM_FUNCTION>(
    # mapping = aes(<MAPPINGS>),
   #  stat = <STAT>, 
   #  position = <POSITION>
 # ) +
 # <FACET_FUNCTION>
```
#Day 2 Assignment 1
```{r}
library(readxl)
API_ER_FSH_AQUA_MT_DS2_en_excel_v2_967 <- read_excel("~/Downloads/API_ER.FSH.AQUA.MT_DS2_en_excel_v2_967.xls", 
    sheet = "Sheet2")
View(API_ER_FSH_AQUA_MT_DS2_en_excel_v2_967) #copied from import
JA_File=API_ER_FSH_AQUA_MT_DS2_en_excel_v2_967 #renaming file
```

#Alter the plot
```{r}
JA_File$Year<- as.numeric(JA_File$Year) #need to define numeric not just label as numeric
JA_File <- na.omit (JA_File)
str(JA_File$Year)
ggplot(data= JA_File) +
 geom_point(
   mapping = aes(x= Year, y=Japan), color="grey" ) +
 geom_point(
   mapping = aes(x= Year, y=Australia), color="black" ) +
  geom_smooth(
    mapping=aes(x=Year, y= Japan), color="grey") +
 geom_smooth(
   mapping=aes(x=Year, y= Japan), group=1, color="grey") +
 geom_smooth(
    mapping= aes(x=Year, y= Australia ), group=2, color= "black")+
  labs(y="Aquaculture Production (Metric Tons)",x="Year", color= "Country")

```
```{r}
ggplot(data=JA_File)+
  geom_point(aes(x=Year, y= Japan, color= "Japan", shape= "Japan")) + 
  geom_point(aes(x=Year, y= Australia, color= "Australia", shape="Australia", shape="Australia")) +
  geom_smooth(aes(x=Year, y= Japan, color= "Japan"), method="loess")+
  geom_smooth(aes(x=Year,y=Australia,color="Australia"),method="loess")+
  labs(y= "Fish Catch (Metric Tons)", x="Year", color= "Country", shape= "Country")
```
